language: go
go:
- tip
script:
- go build
deploy:
  provider: gae
  keyfile: loremsvc-dd66182f509c.json
  project: loremsvc
before_install:
- openssl aes-256-cbc -K $encrypted_82aad19ea289_key -iv $encrypted_82aad19ea289_iv
  -in loremsvc-dd66182f509c.json.enc -out loremsvc-dd66182f509c.json -d
